---
title: "CB-CSNAPNIv1"
author: "Lucas de Lima Casseres"
date: "2023-04-01"
output: html_document: self_contained:no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      cache = TRUE)
```

```{r}
#fig_setup.R
source("FigureSubs/commodity_colorbank.r")
year_labels = c(1997,2002,2007,2012,2017,2022)
crop_labels = c("corn grain","corn silage","wheat","oats","barley","sorghum grain","sorghum silage",
                "potatoes","rye","alfalfa hay","other hay","soybeans","cropland pasture","noncropland pasture",
                "rice","peanuts","grass","winter rye","CGF","CGM","DGS")
meat_labels = c("beef","dairy","swine","sheep","horse","layers","broilers",
                "turkey","goats")
corn_labels = c("Corn not used for ethanol","Corn for dry milling","Corn for wet milling")
NANI_labels = c("Atm N Dep", "Fix N", "Fert N", "Net Food and Feed Imports")
```


```{r}
## This script assigns colors to data categories. It was originally just for commodities, but now it's also for the broader NANI and NAPI contributions

#NANI/NAPI
atmdep = rgb(200/260, 220/260, 254/260) #bluish
biofix = rgb(150/260, 200/260, 10/260) #greenish
agfert = rgb(0.9,0.223,0.180) #redish
nff = rgb(160/260, 39/260, 185/260) #purple, net food and feed
nagfert = rgb(255/260, 255/260, 130/260) #yellow
nffert = rgb(209/260, 165/260, 138/260) #tan, non food fertilizer
det = rgb(255/260, 140/260, 0/260) #orange
P_diet_supp = "#ADCCF6" #light blue

#NANI
NANI_colors = c(atmdep,biofix,agfert,nff,nagfert,nffert)

#NAPI
NAPI_colors = c(agfert,nff,nagfert,nffert,det,P_diet_supp)

#crop commodities
corn = rgb(255/260, 46/260, 67/260) #corn
csilage = rgb(224/300, 67/300, 117/300) #corn silage
wheat = rgb(225/260, 245/260, 254/260) #wheat
oats = rgb(156/260, 39/260, 176/260) #oats
barley = rgb(240/240, 120/240, 146/240) #barley
sorghum = rgb(25/260, 118/260, 210/260) #sorghum
ssilage = rgb(144/260, 202/260, 249/260) #sorghum silage
potatoes = rgb(255/260, 255/260, 141/260) #potatoes
rye = rgb(199/260, 0/260, 57/260) #rye
ahay = rgb(214/260, 183/260, 92/260) #alfalfa hay
nahay = rgb(158/260, 124/260, 22/260) #non alfalfa
soy = rgb(255/260, 182/260, 38/260) #soybeans
cpasture = rgb(127/260, 81/260, 52/260) #cropland pasture
ncpasture = rgb(209/260, 165/260, 138/260) #non cropland
rice = rgb(239/260, 235/260, 233/260) #rice
peanuts = rgb(109/260, 76/260, 65/260) #peanuts
CGF = rgb(244/260, 115/260, 106/260) #CGF
CGM = rgb(244/260, 147/260, 141/260) #CGM
DGS = rgb(244/260, 185/260, 181/260) #DGS
etoh = rgb(247/260, 29/260, 127/260) #ethanol

# Crop commodities
corn = rgb(255/260, 46/260, 67/260)        # corn
csilage = rgb(224/300, 67/300, 117/300)    # corn silage
wheat = rgb(225/260, 245/260, 254/260)     # wheat
oats = rgb(156/260, 39/260, 176/260)       # oats
barley = rgb(240/240, 120/240, 146/240)    # barley
sorghum = rgb(25/260, 118/260, 210/260)    # sorghum
ssilage = rgb(144/260, 202/260, 249/260)   # sorghum silage
potatoes = rgb(255/260, 255/260, 141/260)  # potatoes
rye = rgb(199/260, 0/260, 57/260)          # rye
ahay = rgb(214/260, 183/260, 92/260)       # alfalfa hay
nahay = rgb(158/260, 124/260, 22/260)      # non alfalfa hay
soy = rgb(255/260, 182/260, 38/260)        # soybeans
cpasture = rgb(127/260, 81/260, 52/260)    # cropland pasture
ncpasture = rgb(209/260, 165/260, 138/260) # non cropland pasture
rice = rgb(239/260, 235/260, 233/260)      # rice
peanuts = rgb(109/260, 76/260, 65/260)     # peanuts
CGF = rgb(244/260, 115/260, 106/260)       # CGF
CGM = rgb(244/260, 147/260, 141/260)       # CGM
DGS = rgb(244/260, 185/260, 181/260)       # DGS
etoh = rgb(247/260, 29/260, 127/260)       # ethanol

# New variables
grass = rgb(85/255, 107/255, 47/255)       # grass (olive drab color)
winter_rye = rgb(32/255, 178/255, 170/255) # winter rye (light sea green color)

crop_colors = c(corn,csilage,wheat,oats,barley,sorghum,ssilage,potatoes,rye,ahay,nahay,soy,cpasture,ncpasture,rice,peanuts,grass,winter_rye,CGF,CGM,DGS,etoh)
```


## Results
### 1. NANI
```{r NANItotals_plot,echo=FALSE,fig.width=15,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 1.1: Net Anthropogenic Nitrogen Input (NANI) totals for the US.** Results shown are from the commodity-specific NANI (CSNANI) model.*"}
positives1 <- negatives1 <- NANIBtot_US
positives1[positives1<0] <- 0
negatives1[negatives1>0] <- 0
positives1[3,] <- positives1[3,] + positives1[5,] + positives1[6,]
positives1 <- positives1[1:4,]
# positives2 <- negatives2 <- NANIorigtot_US
# positives2[positives2<0] <- 0
# negatives2[negatives2>0] <- 0
# myrange <- c(min(c(colSums(negatives1),colSums(negatives2)))-1,max(c(colSums(positives1),colSums(positives2)))+1)
myrange <- c(min(colSums(negatives1))-0.1,max(colSums(positives1))+50)

par(mai=c(2, 1, 1, 0.4), xpd=TRUE)
barplot(positives1,
#        main="a) CB-CSNANI",
        ylab="N (10^6 kg)",
        col=NANI_colors,
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
        ylim=myrange, bty='L', width = 1, space = 0.5)
barplot(negatives1,add=TRUE,ylim=rev(myrange),col=NANI_colors, width = 1, space = 0.5)
axis(2)
box()
legend("bottom", inset=c(0,-0.2), legend=c("atmospheric deposition","biological fixation","inorganic fertilizer","net food and feed imports"),ncol=4,  fill=NANI_colors)

# par(mai=c(1, 1, 1, 3), xpd=TRUE)
# myrange <- c(min(c(colSums(negatives1),colSums(negatives2)))-1,max(c(colSums(positives1),colSums(positives2)))+1)
# barplot(positives2,
#         main="b) VB NANI Toolbox",
#         ylab="N (10^3 kg)",
#         col=NANI_colors,
#         axes=FALSE,
#         names.arg = year_labels,
#         cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
#         ylim=myrange, bty='L', width = 1, space = 0.5)
# barplot(negatives2,add=TRUE,ylim=rev(myrange),col=NANI_colors, width = 1, space = 0.5)
# axis(2)
# box()
```

```{r NANItotals_plot,echo=FALSE,fig.width=15,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 1.1: Net Anthropogenic Nitrogen Input (NANI) totals for the US.** Results shown are from the commodity-specific NANI (CSNANI) model.*"}
positives1 <- negatives1 <- NANIBtot_US
positives1[positives1<0] <- 0
negatives1[negatives1>0] <- 0
positives1[3,] <- positives1[3,] + positives1[5,] + positives1[6,]
positives1 <- positives1[1:4,]
# positives2 <- negatives2 <- NANIorigtot_US
# positives2[positives2<0] <- 0
# negatives2[negatives2>0] <- 0
# myrange <- c(min(c(colSums(negatives1),colSums(negatives2)))-1,max(c(colSums(positives1),colSums(positives2)))+1)
myrange <- c(min(colSums(negatives1))-0.1,max(colSums(positives1))+10)

opar = par(oma = c(2,1,1,1))
barplot(positives1,
        ylab="N (10^6 kg)",
        col=NANI_colors,
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.axis=2, cex.main=2,
        ylim=myrange, bty='L', width = 1, space = 0.5)
barplot(negatives1,add=TRUE,ylim=rev(myrange),col=NANI_colors, width = 1, space = 0.5)
axis(2)
par(opar)
legend("bottom", legend=c("atmospheric deposition","biological fixation","fertilizer for food","net food and feed imports"), fill=NANI_colors, ncol=4, inset = -0.05)

# par(mai=c(1, 1, 1, 3), xpd=TRUE)
# myrange <- c(min(c(colSums(negatives1),colSums(negatives2)))-1,max(c(colSums(positives1),colSums(positives2)))+1)
# barplot(positives2,
#         main="b) VB NANI Toolbox",
#         ylab="N (10^3 kg)",
#         col=NANI_colors,
#         axes=FALSE,
#         names.arg = year_labels,
#         cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
#         ylim=myrange, bty='L', width = 1, space = 0.5)
# barplot(negatives2,add=TRUE,ylim=rev(myrange),col=NANI_colors, width = 1, space = 0.5)
# axis(2)
# box()
```
```{r NANItotals_plot,echo=FALSE,fig.width=15,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 1.1: Net Anthropogenic Nitrogen Input (NANI) totals for the US.** Results shown are from the commodity-specific NANI (CSNANI) model.*"}
positives1 <- negatives1 <- NANIBtot_US[2:4,]
positives1[positives1<0] <- 0
negatives1[negatives1>0] <- 0
# positives2 <- negatives2 <- NANIorigtot_US
# positives2[positives2<0] <- 0
# negatives2[negatives2>0] <- 0
# myrange <- c(min(c(colSums(negatives1),colSums(negatives2)))-1,max(c(colSums(positives1),colSums(positives2)))+1)
myrange <- c(min(colSums(negatives1))-0.1,max(colSums(positives1))+10)

par(mai=c(1, 3.6, 1, 0.4), xpd=TRUE, mfrow=c(1,2))
barplot(positives1,
        main="a) CB-CSNANI",
        ylab="N (10^6 kg)",
        col=NANI_colors[2:4],
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
        ylim=myrange, bty='L', width = 1, space = 0.5)
barplot(negatives1,add=TRUE,ylim=rev(myrange),col=NANI_colors[2:4], width = 1, space = 0.5)
axis(2)
box()
legend("topright", inset=c(1.3,0), legend=c("biological fixation","fertilizer for food","net food and feed imports"), fill=NANI_colors[2:4])

# par(mai=c(1, 1, 1, 3), xpd=TRUE)
# myrange <- c(min(c(colSums(negatives1),colSums(negatives2)))-1,max(c(colSums(positives1),colSums(positives2)))+1)
# barplot(positives2,
#         main="b) VB NANI Toolbox",
#         ylab="N (10^3 kg)",
#         col=NANI_colors,
#         axes=FALSE,
#         names.arg = year_labels,
#         cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
#         ylim=myrange, bty='L', width = 1, space = 0.5)
# barplot(negatives2,add=TRUE,ylim=rev(myrange),col=NANI_colors, width = 1, space = 0.5)
# axis(2)
# box()
```
<br>
<br>
<br>
```{r NANI_wsspec_plot,echo=FALSE,fig.width=11,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 1.2: Watershed specific NANI totals** Using new NANI.*"}
ws <- 919:933 ## Lancaster LRS

for(n in 1:nyrs){
  NANI_wsspec[,n] = colSums(NANIBtot[ws,,n])/(10^3)
}
positives <- negatives <- NANI_wsspec
positives[positives<0] <- 0
negatives[negatives>0] <- 0
myrange <- c(min(colSums(negatives))-1,50000)#max(colSums(positives))+1)
par(mai=c(1, 1, 1, 4), xpd=TRUE)
barplot(positives,
      main="NANI for selected watersheds",
      ylab="N (10^3 kg)",
      col=NANI_colors,
      axes=FALSE,
      names.arg = year_labels,
      cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
      ylim=myrange, bty='L', width = 1, space = 0.5)
barplot(negatives,add=TRUE,ylim=rev(myrange),col=NANI_colors, width = 1, space = 0.5)
axis(2)
box()
legend("topright", inset=c(-0.42,0), legend=c("atmospheric deposition","biological fixation","agricultural fertilizer","net food and feed imports","domestic fertilizer","non-food fertilizer"), fill=NANI_colors)
```
<br>
<br>
<br>
```{r fertandfixN_plot,echo=FALSE,fig.width=15,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 1.3: Total commodity-disaggregated fertilizer (a) and fixation (b) inputs for selected watersheds.***"}
par(mai=c(1, 3.6, 1, 0.4), xpd=TRUE,mfrow=c(1,2))
barplot(t(total_commoddisag_fertN),
        main="a) fertilizer N",
        ylab="N (10^6 kg)",
        col=crop_colors,
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.axis=2, cex.main=2, cex.names = 1,
        ylim=c(0,180), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
legend("topright", inset=c(1.4,0), legend=c(crop_labels),  fill=crop_colors)

par(mai=c(1, 1, 1, 3), xpd=TRUE)
barplot(total_commoddisag_fixN,
        main="b) fixation N",
        ylab="N (10^6 kg)",
        col=crop_colors,
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.axis=2, cex.main=2, cex.names = 1,
        ylim=c(0,180), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

# The reason why 2002 has little amount of fertilizer is because the way that fertilizer is calculated in the model right now is multiplying the productivity, and since the yield was lower than average it got lower fertilizer.
```
<br>
<br>
<br>
```{r meatNperprot_plot,echo=FALSE,fig.width=20,fig.height=15,fig.cap="\\label{fig:Rn`}**Figure 1.5: Fertilizer and Fixation N inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}

year_range = 1:6
par(mai=c(0.5, 4, 0.5, 0.25), xpd=TRUE, mfrow=c(3,2))
meat_type=1 #beef
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="a) beef",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,2), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
legend(cex=2.1,"topright", inset=c(1.18,0), legend=c(crop_labels[major_feeds_for_beef],"other grains"),  fill=c(crop_colors[major_feeds_for_beef],"white"))
#Other grains = CGF, CGM, Wheat, Barley, Sorghum, Rye

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=3 #pork
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="b) pork",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,2), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 4, 0.5, 0.25))
meat_type=2 #milk
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="c) milk",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=6 #eggs
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="d) eggs",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 4, 0.5, 0.25))
meat_type=7 #chicken
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="e) chicken",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=8 #turkey
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="f) turkey",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

```
<br>
```{r meatNperprot_plot,echo=FALSE,fig.width=20,fig.height=15,fig.cap="\\label{fig:Rn`}**Figure 1.5: Fertilizer and Fixation N inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
year_range = 1:6
par(mai=c(0.5, 4, 0.5, 0.25), xpd=TRUE, mfrow=c(3,2))
meat_type=1 #beef
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range])
ManureN=manureNperprot[meat_type,year_range]
AmmoniaN=NH3perMprot[meat_type,year_range]
ManureN=ManureN-AmmoniaN
#this combines the minor feeds into a single category

barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds,ManureN,AmmoniaN), #N requirements of meat products over time
        main="a) beef",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,5), bty='L', width = 2, space = 0.5)
axis(2,cex.axis=1.5)
box()
legend(cex=2.1,"topright", inset=c(1.18,0), legend=c(crop_labels[major_feeds_for_beef],"other grains"),  fill=c(crop_colors[major_feeds_for_beef],"white"))
#Other grains = CGF, CGM, Wheat, Barley, Sorghum, Rye

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=3 #pork
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="b) pork",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,2.5), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 4, 0.5, 0.25))
meat_type=2 #milk
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="c) milk",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=6 #eggs
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="d) eggs",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 4, 0.5, 0.25))
meat_type=7 #chicken
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="e) chicken",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=8 #turkey
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Nimpacts_major_feeds=fertNperMprot[meat_type,major_feeds_for_beef,year_range]+fixNperMprot[meat_type,major_feeds_for_beef,year_range]
Nimpacts_minor_feeds=colSums(fertNperMprot[meat_type,minor_feeds_for_beef,year_range])+colSums(fixNperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
barplot(rbind(Nimpacts_major_feeds,Nimpacts_minor_feeds), #N requirements of meat products over time
        main="f) turkey",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
```
<br>
<br>
```{r meatNperprot_plot,echo=FALSE,fig.width=20,fig.height=15,fig.cap="\\label{fig:Rn`}**Figure 1.5: Fertilizer and Fixation N inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
year_range = 1:5
par(mai=c(0.5, 4, 0.5, 0.25), xpd=TRUE, mfrow=c(3,2))
meat_type=1 #beef

Fertilizer=colSums(fertNperMprot[meat_type,,year_range])
Fixation=colSums(fixNperMprot[meat_type,,year_range])
ManureN=manureNperprot[meat_type,year_range]
AmmoniaN=NH3perMprot[meat_type,year_range]

barplot(rbind(Fertilizer,Fixation,ManureN,AmmoniaN), #N requirements of meat products over time
        main="a) beef",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,3.5), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
legend(cex=2.1,"topright", inset=c(1.18,0), legend=c("Fertilizer", "N Fixation", "Manure-N", "NH3-N"),  fill=c(crop_colors[major_feeds_for_beef],"white"))
#Other grains = CGF, CGM, Wheat, Barley, Sorghum, Rye

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=3 #pork

Fertilizer=colSums(fertNperMprot[meat_type,,year_range])
Fixation=colSums(fixNperMprot[meat_type,,year_range])
ManureN=manureNperprot[meat_type,year_range]
AmmoniaN=NH3perMprot[meat_type,year_range]

barplot(rbind(Fertilizer,Fixation,ManureN,AmmoniaN), #N requirements of meat products over time
        main="b) pork",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,2.5), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 4, 0.5, 0.25))
meat_type=2 #milk

Fertilizer=colSums(fertNperMprot[meat_type,,year_range])
Fixation=colSums(fixNperMprot[meat_type,,year_range])
ManureN=manureNperprot[meat_type,year_range]
AmmoniaN=NH3perMprot[meat_type,year_range]

barplot(rbind(Fertilizer,Fixation,ManureN,AmmoniaN), #N requirements of meat products over time
        main="c) milk",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=6 #eggs

Fertilizer=colSums(fertNperMprot[meat_type,,year_range])
Fixation=colSums(fixNperMprot[meat_type,,year_range])
ManureN=manureNperprot[meat_type,year_range]
AmmoniaN=NH3perMprot[meat_type,year_range]

barplot(rbind(Fertilizer,Fixation,ManureN,AmmoniaN), #N requirements of meat products over time
        main="d) eggs",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 4, 0.5, 0.25))
meat_type=7 #chicken

Fertilizer=colSums(fertNperMprot[meat_type,,year_range])
Fixation=colSums(fixNperMprot[meat_type,,year_range])
ManureN=manureNperprot[meat_type,year_range]
AmmoniaN=NH3perMprot[meat_type,year_range]

barplot(rbind(Fertilizer,Fixation,ManureN,AmmoniaN), #N requirements of meat products over time
        main="e) chicken",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 3.6))
meat_type=8 #turkey

Fertilizer=colSums(fertNperMprot[meat_type,,year_range])
Fixation=colSums(fixNperMprot[meat_type,,year_range])
ManureN=manureNperprot[meat_type,year_range]
AmmoniaN=NH3perMprot[meat_type,year_range]

barplot(rbind(Fertilizer,Fixation,ManureN,AmmoniaN), #N requirements of meat products over time
        main="f) turkey",
        ylab="kg N input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white"),
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,1.8), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
```
<br>
```{r meatNperprot_plot,echo=FALSE,fig.width=20,fig.height=15,fig.cap="\\label{fig:Rn`}**Figure 1.5: Fertilizer and Fixation N inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
year_range = 5 # 2017

crop_types=c(1,2,3,4,5,9,10,11,12,18,19)


Fertilizer=c((fertNperCprot[crop_types,year_range]))
Fixation=c((fixNperCprot[crop_types,year_range]))

# Adjust margins
par(mar = c(5, 7, 4, 2) + 0.1)  # c(bottom, left, top, right)


barplot(rbind(Fertilizer,Fixation), #N requirements of meat products over time
        ylab="kg N / kg protein",
        axes=FALSE,
        names.arg = c(crop_labels[crop_types]),col = c("red", "green"),
        cex.lab=3, cex.axis=3, cex.main=3, cex.names = 2.5,
        ylim=c(0,.5), bty='L', width = .5, space = 0.5)

axis(2.5,cex.axis=3,at = seq(0, 0.5,0.1))

legend("topright", inset=c(0.1,0.1), legend=c("Fertilizer", "N Fixation"),  fill=c("red", "green"),cex=2.1)

box()

```
<br>
```{r meatNperprot_plot,echo=FALSE,fig.width=20,fig.height=15,fig.cap="\\label{fig:Rn`}**Figure 1.5: Fertilizer and Fixation N inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
year_range = 5 # 2017

animal_types=c(1,2,3,6,7,8)
crop_types=c(1,2,3,4,5,9,10,11,12,18,19)


Fertilizer=c(rowSums(fertNperMprot[animal_types,,year_range]))
Fixation=c(rowSums(fixNperMprot[animal_types,,year_range]))
ManureN=c(manureNperprot[animal_types,year_range])
AmmoniaN=c(NH3perMprot[animal_types,year_range])

# Adjust margins
par(mar = c(5, 6, 4, 2) + 0.1)  # c(bottom, left, top, right)


barplot(rbind(Fertilizer,Fixation, ManureN, AmmoniaN), #N requirements of meat products over time
        ylab="kg N / kg protein",
        axes=FALSE,
        names.arg = c(meat_labels[animal_types]),col = c("red", "green", "blue","purple"),
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2.5,
        ylim=c(0,3.5), bty='L', width = 1, space = 0.5)

axis(2.5,cex.axis=2.5,at = seq(0, 3.5, 0.5))

legend("topright", inset=c(0.1,0.1), legend=c("Fertilizer", "N Fixation", "Manure", "Ammonia"),  fill=c("red", "green","blue","purple","white"),cex=2.1)

box()

```
<br>
```{r meatNperprot_plot,echo=FALSE,fig.width=20,fig.height=15,fig.cap="\\label{fig:Rn`}**Figure 1.5: Fertilizer and Fixation N inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
year_range = 5 # 2017

animal_types=c(1,2,3,6,7,8)
crop_types=c(1,2,3,4,5,9,10,11,12,18,19,20)


Fertilizer=c(rowSums(fertNperMprot[animal_types,,year_range]),fertNperCprot[crop_types,year_range])
Fixation=c(rowSums(fixNperMprot[animal_types,,year_range]),fixNperCprot[crop_types,year_range])
ManureN=c(manureNperprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
AmmoniaN=c(NH3perMprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
ManureN <- ManureN-AmmoniaN

if(wr_scenario==0 & grass_scenario==1){
  Fertilizer=Fertilizers=c(rowSums(fertNperMprot[animal_types,,year_range]),fertNperCprot[crop_types,year_range])
  Fixation=Fixations=c(rowSums(fixNperMprot[animal_types,,year_range]),fixNperCprot[crop_types,year_range])
  ManureN=ManureNs=c(manureNperprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
  AmmoniaN=AmmoniaNs=c(NH3perMprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
  ManureN=ManureNs <- ManureNs-AmmoniaNs
}

if(wr_scenario==1 & grass_scenario==0){
  Fertilizer=Fertilizerwr=c(rowSums(fertNperMprot[animal_types,,year_range]),fertNperCprot[crop_types,year_range])
  Fixation=Fixationwr=c(rowSums(fixNperMprot[animal_types,,year_range]),fixNperCprot[crop_types,year_range])
  ManureN=ManureNwr=c(manureNperprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
  AmmoniaNwr=c(NH3perMprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
  ManureN=ManureNwr <- ManureNwr-AmmoniaNwr
}
if(wr_scenario==1& grass_scenario==1){
  Fertilizer=Fertilizerwrs=c(rowSums(fertNperMprot[animal_types,,year_range]),fertNperCprot[crop_types,year_range])
  Fixation=Fixationwrs=c(rowSums(fixNperMprot[animal_types,,year_range]),fixNperCprot[crop_types,year_range])
  ManureN=ManureNwrs=c(manureNperprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
  AmmoniaN=AmmoniaNwrs=c(NH3perMprot[animal_types,year_range],0,0,0,0,0,0,0,0,0,0,0,0)
  ManureN=ManureNwrs <- ManureNwrs-AmmoniaNwrs
}
# Adjust margins
par(mar = c(5, 6, 4, 2) + 0.1)  # c(bottom, left, top, right)


barplot(rbind(Fertilizer,Fixation,ManureN,AmmoniaN), #N requirements of meat products over time
        ylab="kg N / kg protein",
        axes=FALSE,
        names.arg = c(meat_labels[animal_types],crop_labels[crop_types]),col = c("red", "green", "blue", "purple"),
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 1,
        ylim=c(0,3.5), bty='L', width = 1, space = 0.5)

axis(2,cex.axis=1.5,at = seq(0, 3.5, 0.5))

legend("topright", inset=c(0.1,0.1), legend=c("Fertilizer", "N Fixation", "Manure-N", "NH3-N"),  fill=c("red", "green", "blue", "purple","white"),cex=2.1)

box()

```
<br>
```{r meatNperprot_plot,echo=FALSE,fig.width=20,fig.height=15,fig.cap="\\label{fig:Rn`}**Figure 1.5: Fertilizer and Fixation N inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
year_range = 5 # 2017

animal_types=c(1,2,3,6,7,8)
crop_types=c(1,2,3,4,5,9,10,11,12,18,19)


Fertilizerm=rowSums(fertNpermeat[animal_types,,year_range])
Fixationm=rowSums(fixNpermeat[animal_types,,year_range])
ManureNm=manureNpermeat[year_range,animal_types]
AmmoniaNm=NH3permeat[year_range,animal_types]
ManureNm <- ManureNm-AmmoniaNm
# Adjust margins
par(mar = c(5, 6, 4, 2) + 0.1)  # c(bottom, left, top, right)


barplot(rbind(Fertilizerm,Fixationm,ManureNm,AmmoniaNm), #N requirements of meat products over time
        ylab="kg N / kg protein",
        axes=FALSE,
        names.arg = c(meat_labels[animal_types]),col = c("red", "green", "blue", "purple"),
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 1,
        ylim=c(0,3.5), bty='L', width = 1, space = 0.5)

axis(2,cex.axis=1.5,at = seq(0, 3.5, 0.5))

legend("topright", inset=c(0.1,0.1), legend=c("Fertilizer", "N Fixation", "Manure-N", "NH3-N"),  fill=c("red", "green", "blue", "purple","white"),cex=2.1)

box()

```
<br>
```{r}
df = data.frame(
  names=rep(crop_labels[crop_types],5),
  fertelizer=c(fertNperCprot[c(1,2,3,4,5,9,10,11,12,18,19),]+fixNperCprot[c(1,2,3,4,5,9,10,11,12,18,19),]),
  year=rep(year_labels,each=length(c(1,2,3,4,5,9,10,11,12,18,19)))
)

# Create the ggplot boxplot
# ggplot(df, aes(x = names, y = fertelizer)) +
#   geom_boxplot(fill = "gold") +
#   theme_minimal() +
#   labs(y="kg N / kg protein")+
#   theme(axis.text.x = element_text(size=14,angle = 30, vjust = 1.1, hjust = 1),
#         axis.title.x = element_blank(),
#         axis.text.y = element_text(size=14),
#         axis.title.y = element_text(size=16),
#         panel.border = element_rect(color = "Black", fill=NA, linewidth =1 ))

# Calculate the mean and standard deviation for each group
summary_df <- aggregate(fertelizer ~ names, df, function(x) c(mean = mean(x), sd = sd(x)))

# Create the ggplot bar plot with error bars
ggplot(summary_df, aes(x = names, y = fertelizer.mean, fill = "gold")) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = fertelizer$mean - fertelizer$sd, ymax = fertelizer$mean + fertelizer$sd), 
                width = 0.4,                    # Width of the error bars
                position = position_dodge(0.9)) + # Position of the error bars
  theme_minimal() +
  labs(y = "kg N / kg protein") +
  theme(axis.text.x = element_text(size = 14, angle = 30, vjust = 1.1, hjust = 1),
        axis.title.x = element_blank(),
        axis.text.y = element_text(size = 14),
        axis.title.y = element_text(size = 16),
        panel.border = element_rect(color = "black", fill = NA, size = 1))  # Add a box around the plot

```

<br>
```{r}
# Set the size of the plotting device
options(repr.plot.width = 10, repr.plot.height = 8)

# Adjust margins
par(mar = c(5, 6, 4, 2) + 0.1)  # c(bottom, left, top, right)

barplot(
  rbind(Fertilizer, Fixation, ManureN, AmmoniaN), # N requirements of meat products over time
  ylab = "kg N / kg protein",
  axes = FALSE,
  names.arg = c(meat_labels[animal_types], crop_labels[crop_types]),
  density = c(20, 17, 19, 23), # Different patterns for each bar
  angle = c(280, 45, 90, 11),
  cex.lab = 2, cex.axis = 3, cex.main = 3, cex.names = 2,
  ylim = c(0, 3.5), bty = 'L', width = 1, space = 0.5
)

axis(2, cex.axis = 1.5, at = seq(0, 3.5, 0.5))


legend(
  "topright", inset = c(0.1, 0.1),
  legend = c("Fertilizer", "N Fixation", "Manure-N", "NH3-N"),
  fill = c("black", "black", "black", "black"),
  density = c(20, 17, 19, 23), # Corresponding patterns for the legend
  angle = c(280, 45, 90, 11),
  cex = 1
)

```

<br>
```{r}
# Sankey Diagram ####
library(tidyverse)
library(data.table)
library(networkD3)

cropsimported <- colSums(feedN4anim[,,5])-(colSums(Ckgws[,,5])*cropdata[,1]*cropdata[,2])
for (i in 1:20) {
  if (cropsimported[i]<0) {cropsimported[i] <- 0}
}

links <- data.table(
  source = c(rep(0, 20),rep(21, 20),rep(22,20),rep(1:20, each=19),1:20,23:41,23:41,23:41),
  target = c(1:20,1:20,1:20,rep(23:41,20),rep(42,39),rep(43,19),rep(44,19)),
  value = c(as.integer(CfertNtot[,5]),colSums(CfixNwswE[,,5]),cropsimported,c(feedN4anim[,,5]),colSums(C4humanN[,,5]),colSums(animN[,,5]),colSums(kgmanureNrec450[,,5]),colSums(kgNH3[,,5])))

links <- links[links$value>0]
links <- links[links$value>0]

nodes <- data.table(name= c("Nitrogen Fertilizer",cropareaharvested_key[2:21,1],"Nitrogen Fixation","Net Food & Feed",animpopcnty_key[1,-1],"Food","Manure","NH3") )

sankeyNetwork(Links = links, Nodes = nodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              colourScale = JS("d3.scaleOrdinal(d3.schemeCategory20);"),
              fontSize = 15, nodeWidth = 20,
              nodePadding = 8.5, iterations = 0, height = NULL, width = NULL)
```

```{r}
# Sankey Diagram ####
library(tidyverse)
library(data.table)
library(networkD3)

cropsimported <- colSums(feedN4anim[,,5])-(colSums(Ckgws[,,5])*cropdata[,1]*cropdata[,2])
for (i in 1:20) {
  if (cropsimported[i]<0) {cropsimported[i] <- 0}
}

majorgrains <- c(1:2,10:12,20)
othercrops <-  setdiff(1:20,majorgrains)

meatfeed <- data.frame("beef"= colSums(feedN4anim[c(1,10,11,13,15),,5]),
                       "dairy"= colSums(feedN4anim[c(2,12,14,16),,5]),
                       "swine"= colSums(feedN4anim[c(3,4),,5]),
                       "layers"= (feedN4anim[5,,5]),
                       "broilers"= colSums(feedN4anim[c(7,8),,5]),
                       "turkey"= colSums(feedN4anim[c(6,9),,5]),
                       "otheranim"= colSums(feedN4anim[c(17,18,19),,5]))

meatfeedMG <- meatfeed[majorgrains,]
meatfeedOC <- colSums(meatfeed[othercrops,])


links <- data.table(
  source = c(rep(0, 7),rep(8, 7),rep(9, 7),rep(1:6,7),rep(7,7),1:7,10:16,18),
  target = c(1:7,1:7,1:7,rep(10:16,each=6),10:16,rep(17,7),rep(18,7),0),
  value = c(as.integer(CfertNtot[majorgrains,5]),sum(as.integer(CfertNtot[othercrops,5])), # Fertilizer
            colSums(CfixNwswE[,,5])[majorgrains],sum(CfixNwswE[,othercrops,5]), # Fixation
            cropsimported[majorgrains],sum(cropsimported[othercrops]), #NFF
            unlist(meatfeedMG),unlist(meatfeedOC), #Animals Feed
            colSums(C4humanN[,,5])[majorgrains],sum(C4humanN[,othercrops,5]), #People
            sum(kgmanureNrec450[,c(1,10,11,13,15),5]),sum(kgmanureNrec450[,c(2,12,14,16),5]),sum(kgmanureNrec450[,c(3,4),5]),sum(kgmanureNrec450[,5,5]),
            sum(kgmanureNrec450[,c(7,8),5]),sum(kgmanureNrec450[,c(6,9),5]),sum(kgmanureNrec450[,c(17,18,19),5]),500000)
)

links <- links[links$value>0]
links <- links[links$value>0]

nodes <- data.table(name= c("Nitrogen Fertilizer",cropareaharvested_key[majorgrains+1,1], "other crops","Nitrogen Fixation","Imported Feed/Food","Beef","Dairy","Swine","Layers","Broilers","Turkey","Other anim","Food","Manure"))

sankeyNetwork(Links = links, Nodes = nodes, Source = "source",
              Target = "target", Value = "value", NodeID = "name",
              colourScale = JS("d3.scaleOrdinal(d3.schemeCategory20);"),
              fontSize = 15, nodeWidth = 20,
              nodePadding = 8.5, iterations = 0, height = NULL, width = NULL)
```
<br>
```{r}
library(plotly)

# Your R data converted to Plotly format
links <- data.frame(
  source = c(rep(0, 7), rep(8, 7), rep(9, 7), rep(1:6, 7), rep(7, 7), 1:7, 10:16,10:16,10:16),
  target = c(1:7, 1:7, 1:7, rep(10:16, each = 6), 10:16, rep(17, 7), rep(18, 7), rep(17,7),rep(19,7)),
  value = c(
    as.integer(CfertNtot[majorgrains, 5]), # Fertilizer for major crops
    sum(as.integer(CfertNtot[othercrops, 5])), # Fertilizer for minor crops
    colSums(CfixNwswE[, , 5])[majorgrains], # Fixation for major crops
    sum(CfixNwswE[, othercrops, 5]), # Fixation for other crops
    cropsimported[majorgrains], # NFF crops
    sum(cropsimported[othercrops]), # NFF other crops
    unlist(meatfeedMG),
    unlist(meatfeedOC),
    colSums(C4humanN[, , 5])[majorgrains],
    sum(C4humanN[, othercrops, 5]),
    sum(kgmanureNrec450[, c(1, 10, 11, 13, 15), 5]),
    sum(kgmanureNrec450[, c(2, 12, 14, 16), 5]),
    sum(kgmanureNrec450[, c(3, 4), 5]),
    sum(kgmanureNrec450[, 5, 5]),
    sum(kgmanureNrec450[, c(7, 8), 5]),
    sum(kgmanureNrec450[, c(6, 9), 5]),
    sum(kgmanureNrec450[, c(17, 18, 19), 5]),
    #sum(kgmanureNrec450[,,5]),
    sum(animN[,c(1, 10, 11, 13, 15),5]),
    sum(animN[,c(2, 12, 14, 16),5]),
    sum(animN[,c(3,4),5]),
    sum(animN[,5,5]),
    sum(animN[,c(7, 8),5]),
    sum(animN[,c(6, 9),5]),
    sum(animN[,c(17, 18, 19),5]),
    sum(kgNH3[,c(1, 10, 11, 13, 15),5]),
    sum(kgNH3[,c(2, 12, 14, 16),5]),
    sum(kgNH3[,c(3,4),5]),
    sum(kgNH3[,5,5]),
    sum(kgNH3[,c(7,8),5]),
    sum(kgNH3[,c(6,9),5]),
    sum(kgNH3[,c(17,18,19),5])
  )
)

links <- links[links$value > 0, ]

nodes <- data.frame(name = c(
  "Nitrogen Fertilizer",
  cropareaharvested_key[majorgrains + 1, 1],
  "other crops",
  "Nitrogen Fixation",
  "Imported Feed/Food",
  "Beef",
  "Dairy",
  "Swine",
  "Layers",
  "Broilers",
  "Turkey",
  "Other anim",
  "Food",
  "Manure",
  "NH3"
))

# Assign colors to links
link_colors <- c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#d4d4d1", "#a6cee3", "#b2df8a",
                 "#fb9a99", "#fdbf6f", "#cab2d6", "#1f78b4", "#33a02c", "#e31a1c", "#ff7f00",
                 "#6a3d9a", "#a6cee3", "#a67556", "#fb9a99", "#fdbf6f", "#cab2d6")

# Create Sankey diagram using plotly with colored links
fig <- plot_ly(
  type = "sankey",
  orientation = "h",
  node = list(
    pad = 15,
    thickness = 20,
    line = list(color = "black", width = 0.5),
    label = nodes$name
  ),
  link = list(
    source = links$source,
    target = links$target,
    value = links$value,
    color = link_colors[c(rep(1,6),rep(7,4),rep(6,7),rep(c(4,2,3,10,17,10),2),4,17,10,4,17,4,17,10,4,17,10,4,2,3,10,17,10,rep(5,7),4,17,5,1,4,2,3,10,17,1,4,2,3,10,17,18,1,4,2,3,10,17,18)]
  )
)

fig <- fig %>% layout(
  title = "Sankey Diagram",
  font = list(size = 12)
)
config(fig,displayModeBar = FALSE)

fig

```

<br>
```{r}
library(plotly)

# Your R data converted to Plotly format
links <- data.frame(
  source = c(rep(0, 7), rep(8, 7), rep(9, 7), rep(1:6, 7), rep(7, 7), 1:7, 10:16,10:16,10:16),
  target = c(1:7, 1:7, 1:7, rep(10:16, each = 6), 10:16, rep(17, 7), rep(18, 7), rep(17,7),rep(19,7)),
  value = c(
    as.integer(CfertNtot[majorgrains, 5]),
    sum(as.integer(CfertNtot[othercrops, 5])),
    colSums(CfixNwswE[, , 5])[majorgrains],
    sum(CfixNwswE[, othercrops, 5]),
    cropsimported[majorgrains],
    sum(cropsimported[othercrops]),
    unlist(meatfeedMG),
    unlist(meatfeedOC),
    colSums(C4humanN[, , 5])[majorgrains],
    sum(C4humanN[, othercrops, 5]),
    sum(kgmanureNrec450[, c(1, 10, 11, 13, 15), 5]),
    sum(kgmanureNrec450[, c(2, 12, 14, 16), 5]),
    sum(kgmanureNrec450[, c(3, 4), 5]),
    sum(kgmanureNrec450[, 5, 5]),
    sum(kgmanureNrec450[, c(7, 8), 5]),
    sum(kgmanureNrec450[, c(6, 9), 5]),
    sum(kgmanureNrec450[, c(17, 18, 19), 5]),
    #sum(kgmanureNrec450[,,5]),
    sum(animN[,c(1, 10, 11, 13, 15),5]),
    sum(animN[,c(2, 12, 14, 16),5]),
    sum(animN[,c(3,4),5]),
    sum(animN[,5,5]),
    sum(animN[,c(7, 8),5]),
    sum(animN[,c(6, 9),5]),
    sum(animN[,c(17, 18, 19),5]),
    sum(kgNH3[,c(1, 10, 11, 13, 15),5]),
    sum(kgNH3[,c(2, 12, 14, 16),5]),
    sum(kgNH3[,c(3,4),5]),
    sum(kgNH3[,5,5]),
    sum(kgNH3[,c(7,8),5]),
    sum(kgNH3[,c(6,9),5]),
    sum(kgNH3[,c(17,18,19),5])
  )
)

links <- links[links$value > 0, ]

nodes <- data.frame(name = c(
  "Nitrogen Fertilizer",
  cropareaharvested_key[majorgrains + 1, 1],
  "other crops",
  "Nitrogen Fixation",
  "Imported Feed/Food",
  "Beef",
  "Dairy",
  "Swine",
  "Layers",
  "Broilers",
  "Turkey",
  "Other anim",
  "Food",
  "Manure",
  "NH3"
))

# Assign colors to links


# Create Sankey diagram using plotly with colored links
fig <- plot_ly(
  type = "sankey",
  orientation = "h",
  node = list(
    pad = 15,
    thickness = 20,
    line = list(color = "grey", width = 0.5),
    label = nodes$name
  ),
  link = list(
    source = links$source,
    target = links$target,
    value = links$value
  )
)

fig <- fig %>% layout(
  title = "Sankey Diagram",
  font = list(size = 12)
)

config(fig,displayModeBar = FALSE)

```

<br>
```{r}
library(plotly)

# Your R data converted to Plotly format
links <- data.frame(
  source = c(rep(0, 7), rep(8, 7), rep(9, 7), rep(1:6, 7), rep(7, 7), 1:7, 10:16,10:16,rep(19,5),9),
  target = c(1:7, 1:7, 1:7, rep(10:16, each = 6), 10:16, rep(17, 7), rep(18, 7), rep(17,7),c(10,14,11,12,15),19),
  value = c(
    as.integer(CfertNtot[majorgrains, 5]),
    sum(as.integer(CfertNtot[othercrops, 5])),
    colSums(CfixNwswE[, , 5])[majorgrains],
    sum(CfixNwswE[, othercrops, 5]),
    cropsimported[majorgrains],
    sum(cropsimported[othercrops]),
    unlist(meatfeedMG),
    unlist(meatfeedOC),
    colSums(C4humanN[, , 5])[majorgrains],
    sum(C4humanN[, othercrops, 5]),
    sum(kgmanureNrec450[, c(1, 10, 11, 13, 15), 5]),
    sum(kgmanureNrec450[, c(2, 12, 14, 16), 5]),
    sum(kgmanureNrec450[, c(3, 4), 5]),
    sum(kgmanureNrec450[, 5, 5]),
    sum(kgmanureNrec450[, c(7, 8), 5]),
    sum(kgmanureNrec450[, c(6, 9), 5]),
    sum(kgmanureNrec450[, c(17, 18, 19), 5]),
    #sum(kgmanureNrec450[,,5]),
    sum(animN[,c(1, 10, 11, 13, 15),5]),
    sum(animN[,c(2, 12, 14, 16),5]),
    sum(animN[,c(3,4),5]),
    sum(animN[,5,5]),
    sum(animN[,c(7, 8),5]),
    sum(animN[,c(6, 9),5]),
    sum(animN[,c(17, 18, 19),5]),
    (rowSums(diet_animal_byproducts)+rowSums(diet_plant_byproducts))[1]*5.080567e+04, #beef
    (rowSums(diet_animal_byproducts)+rowSums(diet_plant_byproducts))[2]*1.513189e+08, #broilers
    (rowSums(diet_animal_byproducts)+rowSums(diet_plant_byproducts))[3]*5.789817e+05, #dairy
    2.500308045*1.626651e+06, #hogs
    0.481075158*1.121247e+07,
    28784509
    )
)

links <- links[links$value > 0, ]

nodes <- data.frame(name = c(
  "Nitrogen Fertilizer",
  cropareaharvested_key[majorgrains + 1, 1],
  "other crops",
  "Nitrogen Fixation",
  "Imported Feed/Food",
  "Beef",
  "Dairy",
  "Swine",
  "Layers",
  "Broilers",
  "Turkey",
  "Other anim",
  "Food",
  "Manure",
  "Byproducts feed"
))

# Assign colors to links


# Create Sankey diagram using plotly with colored links
fig <- plot_ly(
  type = "sankey",
  orientation = "h",
  node = list(
    pad = 15,
    thickness = 20,
    line = list(color = "grey", width = 0.5),
    label = nodes$name
  ),
  link = list(
    source = links$source,
    target = links$target,
    value = links$value
  )
)

fig <- fig %>% layout(
  title = "Sankey Diagram",
  font = list(size = 12)
)

config(fig,displayModeBar = FALSE)

```
<br>

```{r}
library(ggplot2)
library(sf)

# Read shapefile
shapefile <- st_read("C:/Users/lds5498/OneDrive - The Pennsylvania State University/Desktop/Code/shp/P6Beta_v3_LRSegs_081516.shp")
cbw_shp <- shapefile[shapefile$CBW=="Y",]
cbw_shp <- cbw_shp %>% arrange(FIPS,LndRvrSeg)
rownames(cbw_shp) <- 1:nrow(cbw_shp)

ctiescbw_shp <- summarise(group_by(cbw_shp,cbw_shp$FIPS))

# Read dataframe
NANImap <- data.frame("LndRvrSeg" = CBW_lrs_shp$LndRvrSeg,
                        "NANIAtm" = NANIBtot[,1,5],
                        "NANIFertilizer"=NANIBtot[,3,5],
                        "NANIFix"= NANIBtot[,2,5],
                        "NANIFF" = NANIBtot[,4,5])

merged_data <- merge(cbw_shp, NANImap, by = "LndRvrSeg", all.x = TRUE)
```
```{r}
a <- ggplot() +
  geom_sf(data = merged_data, aes(fill = NANIAtm)) +
    geom_sf(data = ctiescbw_shp, color = "black", fill = NA) +  # Adding another shapefile layer
  scale_fill_gradient(low = "cyan", high = "purple",name="AtmDeposit", 
                      labels = c("5,000,000", "4,000,000", "3,000,000", "2,000,000", "1,000,000"),
                      breaks = c(5000000, 4000000, 3000000, 2000000, 1000000)) +theme_minimal()
b <- ggplot() +
  geom_sf(data = merged_data, aes(fill = NANIFertilizer)) +
  geom_sf(data = ctiescbw_shp, color = "black", fill = NA) +  # Adding another shapefile layer
  scale_fill_gradient(low = "cyan", high = "pink",name="Fertilizer", 
                      labels = c("0", "10e3", "14e4", "77e4", "2.4 10e5"),
                      breaks = c(0, 958.6326, 14244.9624 , 77235.1291 , 250000 )) +theme_minimal()
c <- ggplot() +
  geom_sf(data = merged_data, aes(fill = NANIFix)) +
  geom_sf(data = ctiescbw_shp, color = "black", fill = NA) +  # Adding another shapefile layer
  scale_fill_gradient(low = "blue", high = "red",name="Fixation", 
                      labels = c("5,000,000", "4,000,000", "3,000,000", "2,000,000", "1,000,000"),
                      breaks = c(5000000, 4000000, 3000000, 2000000, 1000000)) +theme_minimal()
d <- ggplot() +
  geom_sf(data = merged_data, aes(fill = NANIFF)) +
  geom_sf(data = ctiescbw_shp, color = "black", fill = NA) +  # Adding another shapefile layer
  scale_fill_gradient(low = "blue", high = "red",name="Imported", 
                      labels = c("5,000,000", "4,000,000", "3,000,000", "2,000,000", "1,000,000"),
                      breaks = c(5000000, 4000000, 3000000, 2000000, 1000000)) +theme_minimal()


library(patchwork)

(a+b)/(c+d)
```


### 2. NAPI
```{r NAPItotals_plot,echo=FALSE,fig.width=15,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 2.1: Net Anthropogenic Phosphorus Input (NAPI) totals for the US.** Results shown are from the commodity-specific NAPI (CSNAPI) model.*"}
positives1 <- negatives1 <- NAPIBtot_US
positives1[positives1<0] <- 0
negatives1[negatives1>0] <- 0
# positives2 <- negatives2 <- NAPIorigtot_US
# positives2[positives2<0] <- 0
# negatives2[negatives2>0] <- 0
# myrange <- c(min(c(colSums(negatives1),colSums(negatives2))-0.1),max(c(colSums(positives1),colSums(positives2)))+0.5)
myrange <- c(min(colSums(negatives1))-0.1,max(colSums(positives1))+0.5)

par(mai=c(1, 1, 1, 4), xpd=TRUE) #, mfrow=c(1,2))
barplot(positives1,
        main="CSNAPI",
        ylab="P (10^6 kg)",
        col=NAPI_colors,
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.main=1.5, cex.names = 1.1,
        ylim=myrange, bty='L', width = 1, space = 0.5)
barplot(negatives1,add=TRUE,axes=FALSE,ylim=rev(myrange),col=NAPI_colors, width = 1, space = 0.5)
axis(2, cex.axis = 1.1)
box()
legend("topright", inset=c(1.3,0), legend=c("fertilizer for food","net food and feed imports","non-ag fertilizer","non-food fertilizer","detergent","animal diet supplements"),  fill=NAPI_colors)

# par(mai=c(1, 1, 1, 3), xpd=TRUE)
# barplot(positives2,
#         main="VB NAPI Toolbox",
#         ylab="P (10^3 kg)",
#         col=NAPI_colors,
#         axes=FALSE,
#         names.arg = year_labels,
#         cex.lab=1.5, cex.main=1.5, cex.names = 1.2,
#         ylim=myrange, bty='L', width = 1, space = 0.5)
# barplot(negatives2,add=TRUE,axes=FALSE,ylim=rev(myrange),col=NAPI_colors, width = 1, space = 0.5)
# axis(2, cex.axis = 1.2)
# box()
```
<br>
<br>
<br>
```{r fertP_plot,echo=FALSE,fig.width=11,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 2.2: Total commodity-disagreggated fertilizer inputs for selected watersheds.***"}
par(mai=c(1, 1, 1, 4), xpd=TRUE)
barplot(t(total_commoddisag_fertP),
        main="Fertilizer P: Total commodity-disaggregated inputs",
        ylab="P (10^3 kg)",
        col=crop_colors,
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
        ylim=c(0,2), bty='L', width = 1, space = 0.5)
axis(2)
box()
legend("topright", inset=c(-0.37,0), legend=c(crop_labels,"Ethanol"),  fill=crop_colors)
```
<br>
<br>
<br>
```{r etohPperL_plot,echo=FALSE,fig.width=11,fig.height=8,fig.cap="\\label{fig:Rn`}***Figure 2.3: Fertilizer P inputs per liter of ethanol fuel from 1987-2012.** This estimate excludes P inputs allocated to ethanol coproducts.*"}
par(mai=c(1, 1, 1, 1), xpd=TRUE)
barplot(unitfertPetoh*10^3,
        main="Fertilizer P inputs per liter of ethanol fuel",
        ylab="g P / L ethanol",
        col=crop_colors[20],
        axes=FALSE,
        names.arg = year_labels,
        cex.lab=1.5, cex.axis=1.5, cex.main=1.5,
        ylim=c(0,7), bty='L', width = 1, space = 0.5)
axis(2)
box()
```
<br>
<br>
<br>
```{r meatPperprot_plot,echo=FALSE,fig.width=20,fig.height=20,fig.cap="\\label{fig:Rn`}**Figure 2.4: Fertilizer and mineral P inputs to animal feeds per kg protein in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
y_max = 0.5
P_supp_color = "#ADCCF6" #light blue
year_range = 1:5
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
yaxis_font_size = 2
xaxis_font_size = 2.5
ylab_font_size = 2.5

par(mai=c(0.5, 5, 0.5, 0.25), xpd=TRUE, mfrow=c(3,2))
meat_type=1 #beef
Pimpacts_major_feeds=fertPperMprot[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perprot[meat_type,year_range]
beefPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
beef_df = data.frame(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp), #N requirements of meat products over time
        main="a) beef",
        ylab="kg P input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=ylab_font_size, cex.axis=3, cex.main=3, cex.names = xaxis_font_size,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2, cex.axis=yaxis_font_size)
box()
legend(cex=2.5,"topright", inset=c(1.18,0), legend=c(crop_labels[major_feeds_for_beef], "other grains","diet supplements"),  fill=c(crop_colors[major_feeds_for_beef],"white",P_supp_color))
#Other grains = CGF, CGM, Wheat, Barley, Sorghum, Rye

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=3 #pork
Pimpacts_major_feeds=fertPperMprot[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perprot[meat_type,year_range]
porkPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
pork_df = data.frame(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp), #N requirements of meat products over time
        main="b) pork",
        ylab="kg P input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=ylab_font_size, cex.axis=3, cex.main=3, cex.names = xaxis_font_size,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2, cex.axis=yaxis_font_size)
box()

par(mai=c(0.5, 5, 0.5, 0.25))
meat_type=2 #milk
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Pimpacts_major_feeds=fertPperMprot[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perprot[meat_type,year_range]
milkPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
milk_df = data.frame(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp), #N requirements of meat products over time
        main="c) milk",
        ylab="kg P input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=ylab_font_size, cex.axis=3, cex.main=3, cex.names = xaxis_font_size,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2, cex.axis=yaxis_font_size)
box()

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=6 #eggs
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Pimpacts_major_feeds=fertPperMprot[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perprot[meat_type,year_range]
eggsPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
eggs_df = data.frame(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp), #N requirements of meat products over time
        main="d) eggs",
        ylab="kg P input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=ylab_font_size, cex.axis=3, cex.main=3, cex.names = xaxis_font_size,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2, cex.axis=yaxis_font_size)
box()

par(mai=c(0.5, 5, 0.5, 0.25))
meat_type=7 #chicken
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Pimpacts_major_feeds=fertPperMprot[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perprot[meat_type,year_range]
chickenPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
chicken_df = data.frame(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp), #N requirements of meat products over time
        main="e) chicken",
        ylab="kg P input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=ylab_font_size, cex.axis=3, cex.main=3, cex.names = xaxis_font_size,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2, cex.axis=yaxis_font_size)
box()

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=8 #turkey
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)
Pimpacts_major_feeds=fertPperMprot[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMprot[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perprot[meat_type,year_range]
turkeyPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
turkey_df = data.frame(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp), #N requirements of meat products over time
        main="f) turkey",
        ylab="kg P input / kg protein",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=ylab_font_size, cex.axis=3, cex.main=3, cex.names = xaxis_font_size,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2, cex.axis=yaxis_font_size)
box()
```

```{r meatPperkcal_plot,echo=FALSE,fig.width=20,fig.height=20,fig.cap="\\label{fig:Rn`}**Figure 2.5: Fertilizer and mineral P inputs to animal feeds per kcal in animal food products from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
y_max = .03
P_supp_color = "#ADCCF6" #light blue
year_range = 1:5
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)

par(mai=c(0.5, 5, 0.5, 0.25), xpd=TRUE, mfrow=c(3,2))
meat_type=1 #beef
Pimpacts_major_feeds=fertPperMkcal[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMkcal[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perkcal[meat_type,year_range]
beefPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp)*10^3,
        main="a) beef",
        ylab="g P input / kcal",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
legend(cex=2.1,"topright", inset=c(1.18,0), legend=c(crop_labels[major_feeds_for_beef], "other grains","diet supplements"),  fill=c(crop_colors[major_feeds_for_beef],"white",P_supp_color))
#Other grains = CGF, CGM, Wheat, Barley, Sorghum, Rye

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=3 #pork
Pimpacts_major_feeds=fertPperMkcal[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMkcal[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perkcal[meat_type,year_range]
porkPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp)*10^3,
        main="b) pork",
        ylab="g P input / kcal",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 5, 0.5, 0.25))
meat_type=2 #milk
Pimpacts_major_feeds=fertPperMkcal[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMkcal[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perkcal[meat_type,year_range]
milkPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp)*10^3,
        main="c) milk",
        ylab="g P input / kcal",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=6 #eggs
Pimpacts_major_feeds=fertPperMkcal[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMkcal[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perkcal[meat_type,year_range]
eggsPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp)*10^3,
        main="d) eggs",
        ylab="g P input / kcal",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 5, 0.5, 0.25))
meat_type=7 #chicken
Pimpacts_major_feeds=fertPperMkcal[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMkcal[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perkcal[meat_type,year_range]
chickenPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp)*10^3,
        main="e) chicken",
        ylab="g P input / kcal",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=8 #turkey
Pimpacts_major_feeds=fertPperMkcal[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPperMkcal[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_perkcal[meat_type,year_range]
turkeyPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp)*10^3,
        main="f) turkey",
        ylab="g P input / kcal",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
```

```{r meatPperkgmeat_plot,echo=FALSE,fig.width=20,fig.height=20,fig.cap="\\label{fig:Rn`}**Figure 2.6: Fertilizer and mineral P inputs to animal feeds per kg animal food product from 1997-2012.** Other grains are CGF, CGM, wheat, barley, sorghum, and rye. CGF, CGM, and DGS stand for corn gluten feed, corn gluten meal, and distiller’s grains and solubles, respectively."}
y_max = .1
P_supp_color = "#ADCCF6" #light blue
year_range = 1:5
major_feeds_for_beef=c(10:11,13:14,12,1:2,19) #reordered to keep grains and forage together
minor_feeds_for_beef=c(3:9,15:18)

par(mai=c(0.5, 5, 0.5, 0.25), xpd=TRUE, mfrow=c(3,2))
meat_type=1 #beef
Pimpacts_major_feeds=fertPpermeat[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPpermeat[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_permeat[meat_type,year_range]
beefPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp),
        main="a) beef",
        ylab="kg P input / kg product",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
legend(cex=2.1,"topright", inset=c(1.18,0), legend=c(crop_labels[major_feeds_for_beef], "other grains","diet supplements"),  fill=c(crop_colors[major_feeds_for_beef],"white",P_supp_color))
#Other grains = CGF, CGM, Wheat, Barley, Sorghum, Rye

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=3 #pork
Pimpacts_major_feeds=fertPpermeat[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPpermeat[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_permeat[meat_type,year_range]
porkPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp),
        main="b) pork",
        ylab="kg P input / kg product",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 5, 0.5, 0.25))
meat_type=2 #milk
Pimpacts_major_feeds=fertPpermeat[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPpermeat[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_permeat[meat_type,year_range]
milkPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp),
        main="c) milk",
        ylab="kg P input / kg product",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=6 #eggs
Pimpacts_major_feeds=fertPpermeat[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPpermeat[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_permeat[meat_type,year_range]
eggsPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp),
        main="d) eggs",
        ylab="kg P input / kg product",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 5, 0.5, 0.25))
meat_type=7 #chicken
Pimpacts_major_feeds=fertPpermeat[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPpermeat[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_permeat[meat_type,year_range]
chickenPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp),
        main="e) chicken",
        ylab="kg P input / kg product",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()

par(mai=c(0.5, 0.75, 0.5, 4.6))
meat_type=8 #turkey
Pimpacts_major_feeds=fertPpermeat[meat_type,major_feeds_for_beef,year_range]
Pimpacts_minor_feeds=colSums(fertPpermeat[meat_type,minor_feeds_for_beef,year_range]) #this combines the minor feeds into a single category
Psupp = Psupp_permeat[meat_type,year_range]
turkeyPinputstotal = colSums(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp))
barplot(rbind(Pimpacts_major_feeds,Pimpacts_minor_feeds,Psupp),
        main="f) turkey",
        ylab="kg P input / kg product",
        col=c(crop_colors[major_feeds_for_beef],"white",P_supp_color),
        axes=FALSE,
        names.arg = year_labels[year_range],
        cex.lab=2, cex.axis=3, cex.main=3, cex.names = 2,
        ylim=c(0,y_max), bty='L', width = 1, space = 0.5)
axis(2,cex.axis=1.5)
box()
```

